spring:
  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
  resources: # Static resources
    static-locations: file:src/main/resources/static/
    cache:
      cachecontrol:
          must-revalidate: true
          max-age: 365d
